language: ruby
cache:
  bundler: true
services:
- redis-server
sudo: required
before_install:
- sudo apt-get update
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database brl_today_clone_test;' -U postgres
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: DNCLtp7gE8Sv8rgshUlYGmWeIrOLb9hlITNgqWMK8BH2+YPK9Yl8s1caI9zLKPDTDMLHf+d5Rh5onxVc11k9CikIIAwy6hVYyYta24ZBdznSzNVcKrQ6io8LzFE4pK8rlT4e2Yzuds8gpi3/buJzRFvDxYUlA2DMZGd7bJsdM4t2PXjmp2ZGjnPwNG01dzyQHdkD3irfwFuGAPsex895sM/WB1ueKr1WOJYQHXOKxEjekrQHf6GU05sh20Clatnkw+iyhG/hujzgcD1UbiryFwat+RWCVRSAAvlYhxbYOkdr7mMnf2nXJoIqhOxODSdz6d8PiP1I9YesZoV/OpzjmfQmxXKVUV1KJaT41pejfMXnWu2aH4bO/JGSBXa+FSmBcaAy4rbwpqK4O1Kax/KEVCZLRylaoo5kuQ+gIGkt/PvRux8dZrrsLG7JtFLMRFqCSoYnb0yar7BH83gVjlBlJgvbWq2Bqkx3ldyinufxdMKD5DCHIY5AxvLLjBYwhKLeLPdJxCzBu0c0+3V77oA+FpqBd6ymHRMP23KYnP9B0kWxf2ruPrZriGntjXsOHm6r3PnDaC95yGHbWmw+pO2ponSkpbNONtOkp7oOJN407DKkf2yjlTM915/m5RKenxfm8q7LEwsUPY3Ndhikig8x5JZa9dBs+DKZGMzmx5G83ZU=
