language: ruby
cache:
  bundler: true
services:
  - redis-server
sudo: required
before_install:
- sudo apt-get update
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database brl_today_clone_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - SECRET_KEY_BASE=a RAILS_ENV=production bundle exec rake assets:precompile
  - bundle exec rspec